[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 1000000
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "solmate/=lib/solmate/src/",
]
auto_detect_solc = true
verbosity = 1
via_ir = true

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
arbitrum_mainnet = "${ARBITRUM_MAINNET_RPC}"
eth_mainnet = "${ETH_MAINNET_RPC}"
blast_testnet = "${BLAST_TESTNET_RPC}"

[etherscan]
arbitrum = {key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api"}
eth = {key = "${ETHERSCAN_KEY}"}
